### ISSUE TITLE
Add support for IConfigurationProvider in NAME.AspNetCore

### ISSUE THREAD

**Issue by Symbianx** [nosinovacao/name-sdk#33]
With Asp.Net Core, the standard behaviour for managing settings is with the use of the `IConfigurationProvider`. 

The dependencies.json should support a new connectionstring Locator `IConfigurationProvider` which takes accepts the `key` element containing the name of the setting [as described in the microsoft documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration) (i.e. *section:subsection:key*).

The `IConfigurationProvider` class is in the *Microsoft.Extensions.Configuration.Abstractions* nuget package, since we don't want to add this dependency in the main NAME package we need to add an extension point in the [`DependenciesReader.ReadDependencies`](https://github.com/nosinovacao/name-sdk/blob/56a68a8a2c7110cfe42677f279b6c14a85742573/src/NAME/DependenciesReader.cs#L49) method that allows the caller to inject custom `IConnectionStringProvider`s.

Furthermore [`NAMEAspNetCoreConfiguration`](https://github.com/nosinovacao/name-sdk/blob/56a68a8a2c7110cfe42677f279b6c14a85742573/src/NAME.AspNetCore/NAMEAspNetCoreConfiguration.cs) should optionally take in the `IConfigurationProvider` and use the new extension point.

**Comment by suvl** [comment]
LGTM
