### ISSUE TITLE
Error "Don’t know elementType=17" with MongoDB version checking

### ISSUE THREAD

**Issue by ctorrao** [nosinovacao/name-sdk#38]
In some scenarios, the MongoDB version checker, cannot read correctly the BSON format for a specific datatype, in this case the timestamp format.

Error message: "[Error] Don’t know elementType=17"

MongoDB version: v3.4.15

DataTypes: https://docs.mongodb.com/manual/reference/operator/query/type/

**Comment by Symbianx** [comment]
There is some field that is being returned now in the serverStatus command which was not sent before.
We should add support for the timestamp datatype (and all other types missing).

[These are all the types we should support, including the one we don't have now.](https://docs.mongodb.com/manual/reference/bson-types/)

[This is the command we use to get the MongoDB version.](https://docs.mongodb.com/manual/reference/command/serverStatus/#behavior)

**Comment by ctorrao** [comment]
it was solved in NAME v1.2.1
